UI fix
Selleo/team-fingerprints pull request #15
Opened 2022-02-21 13:04 UTC by mateuszdobija97

## Done:
- [x] - UI - auto focus at input on adding new category, trend and question
- [x] - UI - change "loading" to "logo"
- [x] - UI - change labels and buttons colour
- [x] - UI - change delete button colour to red
- [x] - UI - display questions randomly
- [x] - UI - greater distance between questions

2022-02-21 13:18 UTC, yetiasg approved these changes

2022-02-21 13:27 UTC, tobob requested changes
I have some feedback

2022-02-21 13:27 UTC, tobob commented on team-fingerprints-web/src/components/Category/CategoryForm/CategoryForm.tsx
> +      inputRef && inputRef.current!.focus()
I would rather use `inputRef.current?.focus?.()` instead of this expression

2022-02-21 13:27 UTC, tobob commented on team-fingerprints-web/src/components/Category/CategoryForm/CategoryForm.tsx
> +      inputRef && inputRef.current!.focus()
normal `inputRef.current?.focus?.()` does not work here? do we need this timeout?

2022-02-21 13:27 UTC, tobob commented on team-fingerprints-web/src/routes/Responses/Edit/utils.ts
> +
missing empty line

2022-02-21 13:27 UTC, tobob commented on team-fingerprints-web/src/routes/Responses/Edit/utils.ts
> +
this method looks strange, can't we simply use https://lodash.com/docs/#shuffle ?

2022-02-22 15:15 UTC, tobob commented
@mateuszdobija97 did you get a notification about feedback?

2022-02-23 07:52 UTC, tobob commented
btw there is an info how to connect commit with an issue:
https://stackoverflow.com/a/60027286/2493361

when a commit is merged with `main` issue is closed automatically

2022-02-25 07:07 UTC, merged