closing: #140: store-profile-informations-per-user-profile-screen
Selleo/team-fingerprints pull request #155
Opened 2022-03-22 12:37 UTC by adam-jachymek

2022-03-22 12:51 UTC, tobob approved these changes

2022-03-22 13:17 UTC, polakowski requested changes

2022-03-22 13:29 UTC, polakowski commented on team-fingerprints-web/src/routes/ProfileDetails/ProfileDetails.tsx
> +        <>
How about guard clause instead of multiline ternary? 🤔

2022-03-23 09:41 UTC, polakowski commented on team-fingerprints-web/src/routes/ProfileDetails/ProfileDetails.tsx
> +            <Skeleton height={73} width={560} mt={6} radius="md" animate />
`key` prop missing

2022-03-23 11:51 UTC, tobob commented on team-fingerprints-web/src/routes/ProfileDetails/ProfileDetails.tsx
> +            <Skeleton height={73} width={560} mt={6} radius="md" animate />
times callback returns index as a first argument, so you can use it as key @adam-jachymek 

`{times(3, (index: number) => (`

2022-03-24 13:21 UTC, polakowski commented on team-fingerprints-web/src/types/models.d.ts
> +export type ProfileSelector = {
I think there's no need to have it in a different file. BTW I also think it's nice to have "props" word in type name to explicitly show it's a props type

```suggestion
export type ProfileSelectorProps = {
```

2022-03-24 14:42 UTC, tobob approved these changes

2022-03-24 14:42 UTC, merged