closing #228: make getting survey results for all
Selleo/team-fingerprints pull request #270
Opened 2022-04-08 08:02 UTC by adam-jachymek

2022-04-08 08:20 UTC, polakowski requested changes

2022-04-08 08:20 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/PublicResponses.tsx
> +    ?.filter((survey) => survey.isPublic)
Try to combine those two filters into one `filter` call so the collection is iterated once

2022-04-08 08:20 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/PublicResponses.tsx
> +    if (data?.length === 1) {
What if data.length is greater than 1? I think the condition should look a little different.

I also suggest using guard clause here

2022-04-08 08:20 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/ShowPublicResults.tsx
> +  >(`surveyFinishedOne-${surveyId}`, async () => {
Why not use array as a query key?

2022-04-10 04:08 UTC, tobob approved these changes

2022-04-10 04:14 UTC, merged