closing #273: filters for public surveys
Selleo/team-fingerprints pull request #280
Opened 2022-04-13 12:19 UTC by adam-jachymek

2022-04-14 06:50 UTC, tobob approved these changes

2022-04-14 06:50 UTC, tobob commented on team-fingerprints-web/src/routes/ProfileDetails/ProfileDetails.tsx
> +  console.log("profile", data);
✂️

2022-04-14 06:50 UTC, tobob commented on team-fingerprints-web/src/routes/ProfileDetails/ProfileDetails.tsx
> +  console.log("initialValues", initialValues);
✂️

2022-04-14 06:50 UTC, tobob commented
please remove some console logs

2022-04-14 12:10 UTC, tobob approved these changes

2022-04-14 13:03 UTC, polakowski requested changes

2022-04-14 13:03 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/ResultsFilters.tsx
> +import { useQuery } from "react-query";
Please sort imports

2022-04-14 13:03 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/FiltersSelect.tsx
> +import { Select } from "@mantine/core";
Please sort imports

2022-04-14 13:03 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/FiltersSelect.tsx
> +  handleChange: any;
Type?

2022-04-14 13:03 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/FiltersSelect.tsx
> +  handleSubmit: any;
Type?

2022-04-14 13:03 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/ResultsFilters.tsx
> +  setFilterValues: any;
Type?

2022-04-15 12:18 UTC, adam-jachymek commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/ResultsFilters.tsx
> +  const { handleSubmit, handleChange, values } = useFormik({
After adding context we will still store the same data twice (filter values in both formik and context)

2022-04-15 13:41 UTC, polakowski commented on team-fingerprints-web/src/routes/PublicResponses/Edit/resultsFilters/ResultsFilters.tsx
> +  const { handleSubmit, handleChange, values } = useFormik({
Let's use formik in context so it's in one place

2022-04-19 09:41 UTC, merged

2022-04-19 09:42 UTC, adam-jachymek commented
merged by bob :D