closing #167: hide delete buttons if survey is public
Selleo/team-fingerprints pull request #331
Opened 2022-04-26 15:02 UTC by adam-jachymek

2022-04-26 15:40 UTC, polakowski requested changes

2022-04-26 15:40 UTC, polakowski commented on team-fingerprints-web/src/LoginGateway.tsx
> +import ShowPublicResults from "./routes/PublicSurveys/PublicSurveyResults/";
```suggestion
import ShowPublicResults from "./routes/PublicSurveys/PublicSurveyResults";
```

2022-04-26 15:40 UTC, polakowski commented on team-fingerprints-web/src/routes/Surveys/Details/Details.tsx
> +              {!survey?.isPublic && (
Do we want to display this button if there's no survey? The same question applies to lines 94 and 132.

BTW `!survey?.isPublic` is repeated, try to avoid repetitions

2022-04-28 11:28 UTC, tobob requested changes

2022-04-28 12:47 UTC, polakowski commented on team-fingerprints-web/src/routes/Surveys/Details/Details.tsx
> +              {!survey?.isPublic && (
`!survey?.isPublic` this expression returns `true` when there's no survey (`survey` variable is undefined or null). I think we shouldn't display button.

PS. Is the question mark even needed here? You check against no `survey` in line 40

2022-04-28 12:49 UTC, tobob commented on team-fingerprints-web/src/routes/Surveys/Details/Details.tsx
> +              {!survey?.isPublic && (
yes, I think that we can omit this question mark

2022-04-29 11:49 UTC, polakowski commented on team-fingerprints-web/src/routes/Surveys/Details/Details.tsx
> +                              {!survey?.isPublic && (
```suggestion
                              {!survey.isPublic && (
```

2022-04-29 12:45 UTC, polakowski approved these changes

2022-04-29 12:53 UTC, tobob approved these changes

2022-04-29 12:56 UTC, merged