closing #180: add 'archive' checkbox to survey edit modal
Selleo/team-fingerprints pull request #332
Opened 2022-04-26 15:23 UTC by adam-jachymek

2022-04-26 15:26 UTC, polakowski requested changes

2022-04-26 15:26 UTC, polakowski commented on team-fingerprints-web/src/components/Survey/SurveyForm/SurveyForm.tsx
> +  console.log("values", values);
✂️

2022-04-26 15:26 UTC, polakowski commented on team-fingerprints-web/src/components/Survey/SurveyForm/SurveyForm.tsx
> +        ></Checkbox>
This is a nitpick but this component can be self-closing

2022-04-27 06:10 UTC, tobob approved these changes

2022-04-29 07:39 UTC, polakowski approved these changes

2022-04-29 08:05 UTC, merged