web/#164-create-modal-to-approve-all-deletions
Selleo/team-fingerprints pull request #348
Opened 2022-05-04 17:28 UTC by adam-jachymek

2022-05-04 18:16 UTC, yetiasg commented on team-fingerprints-api/src/survey-answer/survey-answer.controller.ts
> +  //@UseInterceptors(CacheInterceptor)
Please, uncomment all interceptors

2022-05-05 05:23 UTC, tobob requested changes
please follow my feedback
additionally please create component 
`ButtomWithModalConfirmation` that will utilize your implementation

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/Category/DeleteCategoryButton/DeleteCategoryButton.tsx
> +      modalMsg="Are you sure you want to delete this category?"
please rename to `message`, pleaase don't use short names like `msg`

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/Category/DeleteCategoryButton/DeleteCategoryButton.tsx
> +        style={{ color: "#ff0000", borderColor: "#ff0000" }}
inline style, please create global style for it if needed

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/ModalWrapper/ModalWrapper.tsx
> +      {children}
we have miscommunication in this area ;)

I want to put children inside the modal, rather than outside, currently this is not `ModalWrapper` rather `ContentWithModalConfirmation`

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/ModalWrapper/ModalWrapper.tsx
> +      {children}
what I want you to do is:
0. create `mode` prop with `enum` `confirmation | content`
1. move content of <div 'modal__content'> into use memo
2. inside this memo if mode=confirmation then render the current implementation
3. inside this memo if mode=content then render children

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/ModalWrapper/styles.sass
> +      background-color: #c9c9c9
move to variables

2022-05-05 05:23 UTC, tobob commented on team-fingerprints-web/src/components/ModalWrapper/styles.sass
> +      background-color: #c9c9c9
https://chir.ag/projects/name-that-color/#c9c9c9 to find proper name for color (in this case `silver`)

2022-05-05 15:34 UTC, polakowski commented on team-fingerprints-web/src/components/Category/DeleteCategoryButton/DeleteCategoryButton.tsx
> +        style={{ color: "#ff0000", borderColor: "#ff0000" }}
It would take quite a work to refactor this as Mantine handles colors in a mysterious way. I suggest leaving this as it is (and was before) and create a ticket to refactor this in future.

2022-05-05 15:34 UTC, polakowski commented on team-fingerprints-web/src/components/Category/DeleteCategoryButton/DeleteCategoryButton.tsx
> +        style={{ color: "#ff0000", borderColor: "#ff0000" }}
It would take quite a work to refactor this as Mantine handles colors in a mysterious way. I suggest leaving this as it is (and was before) and create a ticket to refactor this in future.

2022-05-06 13:43 UTC, polakowski approved these changes
:rocket:

2022-05-06 13:44 UTC, tobob approved these changes

2022-05-06 13:44 UTC, merged