web/#284 mobile view header and answering survey
Selleo/team-fingerprints pull request #366
Opened 2022-05-09 17:04 UTC by adam-jachymek

2022-05-10 06:01 UTC, tobob requested changes

2022-05-10 06:02 UTC, ArekJanik requested changes

2022-05-10 11:40 UTC, yetiasg commented on team-fingerprints-api/src/app.module.ts
> -      limit: 20,
limit should not be removed, it can be increased e.g. to 60

2022-05-10 11:43 UTC, tobob commented on team-fingerprints-web/src/styles/base/_breakpoints.sass
> +            @content
bump, we don't need comments in this file

2022-05-10 12:17 UTC, polakowski commented on team-fingerprints-api/src/app.module.ts
> -      limit: 20,
How about ENV? Sometimes we shouldn't have any limit e.g. in development

2022-05-10 12:28 UTC, polakowski commented on team-fingerprints-web/src/components/AppHeader/styles.sass
> +    button
I know it's not your change but please refactor tag-based styles using classes

2022-05-10 12:29 UTC, polakowski commented on team-fingerprints-web/src/styles/base/_breakpoints.sass
> +
✂️ Multiple lines found multiple times in the file, please no multiple empty lines

2022-05-10 12:30 UTC, polakowski commented on team-fingerprints-web/src/styles/application.sass
> +@import 'base/_breakpoints'
```suggestion
@import 'base/breakpoints'
```

2022-05-10 12:32 UTC, polakowski commented on team-fingerprints-web/src/styles/application.sass
> +
✂️

2022-05-10 13:18 UTC, yetiasg approved these changes

2022-05-11 09:37 UTC, polakowski approved these changes
Just revert changes from Edit.tsx

2022-05-12 04:55 UTC, merged

2022-05-12 07:45 UTC, ArekJanik reviewed
To clean this up:
* use variables
* avoid magic number
* go mobile first