[FE] Public results: open modal right away creating filter set
Selleo/team-fingerprints pull request #455
Opened 2022-11-10 12:10 UTC by shirve

### Changes
Improved filter set modal to open right away on filter create

2022-11-10 12:35 UTC, tobob commented
@shirve your implementation is not looking good, it should work only when the user create a filter
now if the user opens results for the company/team (they are persisted on BE) it also automatically opens the modal when entering the results screen


https://user-images.githubusercontent.com/3189332/201093110-f4aba2d0-2550-44d0-9da9-c6bab7338c08.mov

2022-11-10 12:36 UTC, tobob requested changes
invalid implementation, please check company/team results view

2022-11-14 09:24 UTC, tobob requested changes
please don't save whole object, only _id of it

2022-11-14 09:24 UTC, tobob commented on team-fingerprints-web/src/components/FiltersSets/FiltersSets.tsx
> +  const [newestFilterSet, setNewestFilterSet] = useState<FiltersSet>();
@shirve please don't save whole filter set object, rather please save only _id of filterset

2022-11-14 10:05 UTC, shirve commented on team-fingerprints-web/src/components/FiltersSets/FiltersSets.tsx
> +  const [newestFilterSet, setNewestFilterSet] = useState<FiltersSet>();
Applied

2022-11-14 11:13 UTC, tobob approved these changes

2022-11-14 11:13 UTC, merged