[FE] When navigating into screen with list of surveys, automaticaly click on first if there is only one
Selleo/team-fingerprints pull request #501
Opened 2022-11-24 13:42 UTC by shirve

2022-11-25 07:51 UTC, tobob approved these changes

2022-11-25 07:53 UTC, tobob requested changes

2022-11-25 07:53 UTC, tobob commented on team-fingerprints-web/src/components/SurveyList/SurveyList.tsx
> +    if (mappedData?.length === 1) {
please move this into useEffect with additional check if it finish loading
please don't place such code inside useMemo

2022-11-28 08:05 UTC, tobob approved these changes

2022-11-28 08:05 UTC, tobob commented
@shirve please resolve conflicts

2022-11-28 09:33 UTC, Matesty commented
@shirve
- Back button from browser and inside the app doesn't work, once you open the survey
- User should be able to see survey list after clicking 'Survey List' from breadcrumbs (?)
- Should it work the same for own surveys?

![Zrzut ekranu_20221128_102905](https://user-images.githubusercontent.com/72445161/204243015-28ace588-0e85-49e2-af70-2b117b49947a.png)

2022-11-29 07:59 UTC, tobob approved these changes

2022-11-29 10:28 UTC, Matesty commented
@shirve Works good, but still not for own surveys

2022-11-29 10:34 UTC, shirve commented
> @shirve Works good, but still not for own surveys

About that - if there is only one survey in `Own Surveys` and it has not yet been filled do we want to redirect user to it too?

2022-11-29 11:09 UTC, shirve commented
@Matesty you can test it now with Own Surveys

2022-11-29 11:13 UTC, Matesty approved these changes

2022-11-30 08:19 UTC, tobob approved these changes

2022-11-30 08:19 UTC, merged