[F/E] Add cookie policy
Selleo/team-fingerprints pull request #503
Opened 2022-11-24 16:00 UTC by shirve

### Changes
Added cookie policy banner

### Preview
<img width="1440" alt="Screenshot 2022-11-24 at 16 59 35" src="https://user-images.githubusercontent.com/43320967/203826292-778d63eb-3a48-4db6-9e4e-4bff20581864.png">

2022-11-25 07:58 UTC, tobob requested changes
I have some feedback ;)

2022-11-25 07:58 UTC, tobob commented on team-fingerprints-web/src/components/CookiePolicy/CookiePolicy.tsx
> +import { ReactComponent as XCircle } from "assets/XCircle.svg";
order of imports:
```
main libraries - react, react-dom
3rd party libraries
our libraries
components
svgs/icons
styles
```

2022-11-25 07:58 UTC, tobob commented on team-fingerprints-web/src/components/CookiePolicy/CookiePolicy.tsx
> +  const [isVisible, setIsVisible] = useState(true);
please change into:

const [isVisible, setIsVisible] = useState(Cookies.get("cookiePolicy"));

to remove unnecessary const `cookiePolicy`

2022-11-28 08:06 UTC, tobob approved these changes

2022-11-28 10:24 UTC, Matesty commented
@shirve 
- for now without redirection to the cookie policy?

2022-11-28 10:27 UTC, shirve commented
@Matesty 
Correct. The url for cookie policy was not yet provided.

2022-11-28 11:11 UTC, Matesty approved these changes

2022-11-28 12:16 UTC, tobob commented
@shirve please resolve conflicts my merging with main

2022-11-30 07:29 UTC, merged