[FE] mobile view
Selleo/team-fingerprints pull request #544
Opened 2022-12-08 12:23 UTC by shirve

2022-12-08 14:07 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Chart/Chart.tsx
>    // responsive width and height
Does the comment should be here?

2022-12-08 14:22 UTC, shirve commented on team-fingerprints-web/src/components/Chart/Chart.tsx
>    // responsive width and height
Not my piece of code. I guess it's just descriptive for other developers working on this component to know what's going on.

2022-12-08 14:32 UTC, DawidHaratyk requested changes

2022-12-08 14:32 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Chart/Chart.tsx
>    // responsive width and height
Does the comment should be here?

2022-12-12 15:37 UTC, tobob approved these changes

2022-12-12 15:38 UTC, merged