Refactor/integration tests
Selleo/team-fingerprints pull request #569
Opened 2022-12-15 13:12 UTC by DawidHaratyk

Add integration tests for modals components below:
-ModalConfirm
-ModalConfirmTrigger
-ModalTrigger
-ModalWrapper

2022-12-16 07:38 UTC, shirve requested changes

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    await act(() => ref.current?.show());
There is no need to `await` for act as it's not returning promise

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
You can target this modal with `queryByRole("dialog")` and wrapping it inside `waitFor()`
```suggestion
    await waitFor(() => {
      expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    });
```

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    );
I would suggest taking the `ref` with `onConfirmMock` and `render` method outside to the top of your file because it's all unnecessarily duplicated

So on top of your tests you would have:
```
const onConfirmMock = jest.fn();
const ref = createRef<IModalConfirmMethods>();

const renderComponent = () => {
  render(
    <ModalConfirm
      onConfirm={onConfirmMock}
      modalMessage="Modal message"
      ref={ref}
    />
  );
};
```

And then inside your test:

```suggestion
    renderComponent();
```

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirmTrigger/__tests__/ModalConfirmTrigger.spec.tsx
> +    );
Same here, unnecessary duplication

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirmTrigger/__tests__/ModalConfirmTrigger.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Here too - use `queryByRole("dialog")`

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/ModalTrigger.tsx
> +        data-testid="modal-trigger"
You are not using it anywhere ✂️

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/ModalTrigger.tsx
> +    | ReactNode;
Did you just change component logic just to make the test work? 🤨
What's the point of testing `children` type of ReactNode as they haven't been used like that anywhere?

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      );
Same as before - that could be exported outside to avoid code duplication
Since you are passing different `renderTrigger` and `children` props it could look like so:

```
const renderComponent = ({
  renderTrigger,
  children,
}: {
  renderTrigger: (
    changeModalState: (modalVisible: boolean) => void
  ) => ReactNode;
  children: (changeModalState: (modalVisible: boolean) => void) => ReactNode;
}) => {
  render(
    <ModalTrigger renderTrigger={renderTrigger} modalMessage="Modal message">
      {children}
    </ModalTrigger>
  );
};
```

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      const planeRenderTriggerMock = jest.fn();
✈️ ? 
typo

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalWrapper/__tests__/ModalWrapper.spec.tsx
> +      </ModalWrapper>
Same here - render could be extracted:

```
const renderComponent = ({
  modalVisible,
  modalMessage,
  className,
}: {
  modalVisible?: boolean;
  modalMessage?: string;
  className?: string;
} = {}) => {
  render(
    <ModalWrapper
      setModalVisible={setModalVisible}
      modalVisible={modalVisible}
      modalMessage={modalMessage}
      className={className}
    >
      <div>Some modal content</div>
    </ModalWrapper>
  );
};
```

2022-12-16 07:38 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalWrapper/__tests__/ModalWrapper.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Same as before - use `queryByRole("dialog")` with `waitFor()`

2022-12-20 08:49 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    await act(() => ref.current?.show());
Right, done

2022-12-20 08:53 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Right, done :)

2022-12-20 08:57 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    );
Right, done

2022-12-20 09:00 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirmTrigger/__tests__/ModalConfirmTrigger.spec.tsx
> +    );
Right, done

2022-12-20 09:02 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirmTrigger/__tests__/ModalConfirmTrigger.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Right, done

2022-12-20 09:04 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalTrigger/ModalTrigger.tsx
> +        data-testid="modal-trigger"
Right, done

2022-12-20 09:10 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalTrigger/ModalTrigger.tsx
> +    | ReactNode;
No, there was missing ReactNode type in children because we're rendering children as a function or as a ReactNode itself.
I've tested it because in the future, maybe we'll have a case where someone will use children as a ReactNode type in that component

2022-12-20 09:17 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/ModalTrigger.tsx
> +    | ReactNode;
Ahh I see it now, okay 👍

2022-12-20 10:23 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      );
Right, done

2022-12-20 10:28 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      const planeRenderTriggerMock = jest.fn();
Right, do you think emptyRenderTriggerMock variable name will be okay?

2022-12-20 10:30 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      const planeRenderTriggerMock = jest.fn();
It was good I just think you had `plain` in mind

2022-12-20 10:40 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalWrapper/__tests__/ModalWrapper.spec.tsx
> +      </ModalWrapper>
Right, done

2022-12-20 10:42 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalWrapper/__tests__/ModalWrapper.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Right, done

2022-12-20 10:48 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalTrigger/__tests__/ModalTrigger.spec.tsx
> +      const planeRenderTriggerMock = jest.fn();
Okay, emptyRenderTriggerMock variable name is already pushed so I'll leave it as it is, I think it's good as well

2022-12-20 10:51 UTC, tobob approved these changes

2022-12-20 10:51 UTC, tobob commented
@shirve can you take a look?

2022-12-20 10:52 UTC, shirve commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
You missed one modal `queryByRole('dialog')`

2022-12-20 10:56 UTC, shirve approved these changes
Looks good 👍

2022-12-20 11:05 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/Modals/ModalConfirm/__tests__/ModalConfirm.spec.tsx
> +    expect(screen.queryByRole("div", { hidden: true })).not.toBeInTheDocument();
Right, done

2022-12-20 11:42 UTC, merged