Add ErrorLoading test
Selleo/team-fingerprints pull request #579
Opened 2022-12-21 13:54 UTC by typeWolffo

2022-12-21 14:03 UTC, shirve commented on team-fingerprints-web/src/components/ErrorLoading/__test__/ErrorLoading.spec.tsx
> +  });
`window.location.pathname` is equal to `"/"` this whole test instead use `history.location.pathname`

2022-12-22 07:58 UTC, tobob commented on team-fingerprints-web/src/components/ErrorLoading/__test__/__snapshots__/ErrorLoading.spec.tsx.snap
> +
please don't add snapshots, we don't want them inside project, rather check implementation

2022-12-22 07:59 UTC, tobob requested changes
we don't snapshot tests, I don't see any value in them

2023-01-02 21:54 UTC, DawidHaratyk commented on team-fingerprints-web/src/components/ErrorLoading/__test__/ErrorLoading.spec.tsx
> +    render(<ErrorLoading />, { wrapper: BrowserRouter });
Wouldn't it be better if you replace it with

` renderComponent();`

as AppSetup component is already wrapped with Router :)

2023-01-10 07:16 UTC, tobob approved these changes

2023-01-10 07:17 UTC, merged