[FE] routes/EmailWhitelist tests refactor
Selleo/team-fingerprints pull request #582
Opened 2022-12-30 10:23 UTC by shirve

2023-01-03 07:34 UTC, DawidHaratyk requested changes

2023-01-03 07:34 UTC, DawidHaratyk commented on team-fingerprints-web/src/routes/TeamManagement/EmailWhitelist/__tests__/EmailWhitelist.spec.tsx
> +          role: "TEAM_LEADER",
Is TEAM_LEADER appropriate here? The test is describing that user is company admin 

`it("should display remove a leader button if user is company admin", async () => {`

2023-01-04 07:06 UTC, shirve commented on team-fingerprints-web/src/routes/TeamManagement/EmailWhitelist/__tests__/EmailWhitelist.spec.tsx
> +          role: "TEAM_LEADER",
This is correct as it doesn't refer to the user performing the action but to the list of `roles`  being passed on through props which we are displaying in this component. The test checks for proper displaying of `Remove a leader` button which can only appear if someone has a `TEAM_LEADER` role thus why we need user with that role.

2023-01-05 12:10 UTC, DawidHaratyk commented on team-fingerprints-web/src/routes/TeamManagement/EmailWhitelist/__tests__/EmailWhitelist.spec.tsx
> +          role: "TEAM_LEADER",
Oh, now I understand, I thought TEAM_LEADER was a logged user, my bad :)

2023-01-10 07:17 UTC, tobob approved these changes

2023-01-10 07:18 UTC, merged