[FE] LandingPage specs
Selleo/team-fingerprints pull request #603
Opened 2023-01-12 08:43 UTC by shirve

### Changes
- Added `LandingPage` specs
- Moved `setupTests` localStorage mock to the spec that needed it because it was causing problems in other specs
- Updated specs that stopped working after changing `profile` factory

2023-01-12 10:05 UTC, DawidHaratyk requested changes

2023-01-12 10:05 UTC, DawidHaratyk commented on team-fingerprints-web/src/setupTests.ts
> -// access to localStorage
Can I know why did you remove these localStorage lines? Some files are managing local storage

2023-01-12 10:08 UTC, DawidHaratyk requested changes

2023-01-12 10:08 UTC, DawidHaratyk commented on team-fingerprints-web/src/setupTests.ts
> -
Can I know why did you remove these localStorage lines? Some files are managing local storage

2023-01-12 10:12 UTC, shirve commented on team-fingerprints-web/src/setupTests.ts
> -
It got moved to the spec that was using it as it was causing problems with mocking values into localStorage elsewhere

2023-01-17 08:08 UTC, tobob commented
@shirve merge conflicts ;)

2023-01-17 08:17 UTC, merged